changelog:
  categories:
    - title: Breaking Changes
      labels:
        - breaking
    - title: Features
      labels:
        - enhancement
        - feat
    - title: Bug Fixes
      labels:
        - bug
        - fix
    - title: Documentation
      labels:
        - documentation
        - docs
    - title: Dependency Updates
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - "*"
